# Generated by Django 5.2.17 on 2026-10-01 09:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("audit_sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "audit_head",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("operation", models.CharField(max_length=80)),
                ("destination", models.CharField(max_length=253)),
                ("max_cost_cents", models.PositiveIntegerField()),
                ("approval_required", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("reviewer", "Reviewer"),
                            ("operator", "Operator"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("limit_cents", models.PositiveBigIntegerField(default=10000)),
                ("reserved_cents", models.PositiveBigIntegerField(default=0)),
                ("spent_cents", models.PositiveBigIntegerField(default=0)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("kind", models.CharField(max_length=50)),
                ("actor", models.CharField(max_length=150)),
                ("payload", models.JSONField()),
                ("previous", models.CharField(max_length=64)),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requester", models.CharField(max_length=160)),
                ("idempotency_key", models.CharField(max_length=100)),
                ("fingerprint", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=80)),
                ("destination", models.CharField(max_length=253)),
                ("cost_cents", models.PositiveIntegerField()),
                ("arguments_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("denied", "denied"),
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("leased", "leased"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("lease_digest", models.CharField(blank=True, max_length=64)),
                ("leased_at", models.DateTimeField(null=True)),
                ("result_digest", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="core.policy"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workspace"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                fields=("workspace", "operation", "destination", "revision"),
                name="unique_policy_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="unique_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.UniqueConstraint(
                fields=("workspace", "sequence"), name="unique_audit_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.UniqueConstraint(
                fields=("workspace", "requester", "idempotency_key"),
                name="unique_action_idempotency",
            ),
        ),
    ]
