# Generated by Django 5.2.17 on 2026-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("window", models.PositiveBigIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("key", "window"), name="unique_login_bucket")
                ],
            },
        ),
    ]
